name: Push Notify
# ë©”ì¸ ë¸Œëœì¹˜ì— ì´ë²¤íŠ¸(Push,Merge)ê°€ ë°œìƒí–ˆì„ë•Œ ìŠ¬ë™ì— ì•Œë¦¼ ë°œì†¡
on:
  push:
    branches: [ main ]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send webhook with commit message
        run: |
          curl -X POST ${{ secrets.WEB_HOOK_URL }} \
            -H "Content-Type: application/json" \
            -d '{
              "text": "ğŸ“¢ `${{ github.actor }}`ê°€ main ë¸Œëœì¹˜ì— í‘¸ì‹œí–ˆìŠµë‹ˆë‹¤!\nğŸ“ ì»¤ë°‹ ë©”ì‹œì§€: `${{ github.event.head_commit.message }}`"
            }'